export const GET_MENUS_REQUEST = 'GET_MENUS_REQUEST';
export const GET_MENUS_SUCCESS = 'GET_MENUS_SUCCESS';
export const GET_MENUS_FAILURE = 'GET_MENUS_FAILURE';
export const SET_MENUS = "SET_MENUS";

export const LOADING_START = "LOADING_START";
export const LOADING_END = "LOADING_END";